# Setup
title:               'Weakly Supervised'
tagline:             'Writings about stuff'
description:         'Not sure what this will be about. Will post updates on <a href="https://twitter.com/HermanKamper" target="_blank">Twitter</a>.'
url:                 'http://www.weaklysupervised.com'
baseurl:             ''
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Herman Kamper
  url:               https://www.kamperh.com
  email:             kamperh@gmail.com

# Gems
plugins:
  - jekyll-paginate

# # Custom vars
# version:             1.1.0
# google_analytics_id: #UA-XXXX-Y
